### ISSUE TITLE
loginitems -a on loginitems itself

### ISSUE THREAD

**Issue by u1i** [OJFord/loginitems#4]
I'd like to have a simple script run on login - before any of the others:

loginitems -d "Cisco Webex Meetings"

Is that possible?

**Comment by OJFord** [comment]
I believe any executable should work, though off-hand I'm not sure if I've ever used it with non-`.app`s (which aren't really executables, at least in the same sense).

So I _think_:
```
$ echo -e '#!/bin/sh\nloginitems -d "Cisco Webex Meetings"' > /usr/local/bin/loginitems-rm-webex
$ chmod +x /usr/local/bin/loginitems-rm-webex
$ loginitems -a 'Remove Webex' -p /usr/local/bin/loginitems-rm-webex
```

should work.

However, I'd question if that's really going to achieve what you want - if something's putting Webex back in the list (perhaps when you have to manually launch it, it puts itself there?) then don't you need to run `loginitems -d` after that, and before next login? i.e. on logout?

**Comment by OJFord** [comment]
I'm going to close this issue because I don't feel that there's any change to be made in `loginitems`, but feel free to reply if the above explanation isn't clear, or reopen if you think there is something missing.
